/********************************************************************
* PWFormatDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PWFormatDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePWFormatDict();
extern void G__cpp_setup_inheritancePWFormatDict();
extern void G__cpp_setup_typetablePWFormatDict();
extern void G__cpp_setup_memvarPWFormatDict();
extern void G__cpp_setup_globalPWFormatDict();
extern void G__cpp_setup_memfuncPWFormatDict();
extern void G__cpp_setup_funcPWFormatDict();
extern void G__set_cpp_environmentPWFormatDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/PWSegment.h"
#include "/user/benderp/Programs/GRETINA/include/PWFragment.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PWFormatDictLN_TClass;
extern G__linked_taginfo G__PWFormatDictLN_TBuffer;
extern G__linked_taginfo G__PWFormatDictLN_TMemberInspector;
extern G__linked_taginfo G__PWFormatDictLN_TObject;
extern G__linked_taginfo G__PWFormatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PWFormatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PWFormatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PWFormatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PWFormatDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PWFormatDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__PWFormatDictLN_TVector3;
extern G__linked_taginfo G__PWFormatDictLN_TGEBEvent;
extern G__linked_taginfo G__PWFormatDictLN_TGEBEventcLcLTPWHit;
extern G__linked_taginfo G__PWFormatDictLN_TGEBEventcLcLTPWBank;
extern G__linked_taginfo G__PWFormatDictLN_PWSegment;
extern G__linked_taginfo G__PWFormatDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__PWFormatDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__PWFormatDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PWFormatDictLN_TH2F;
extern G__linked_taginfo G__PWFormatDictLN_PWFragment;
extern G__linked_taginfo G__PWFormatDictLN_vectorlEPWSegmentcOallocatorlEPWSegmentgRsPgR;
extern G__linked_taginfo G__PWFormatDictLN_vectorlEPWSegmentcOallocatorlEPWSegmentgRsPgRcLcLiterator;
extern G__linked_taginfo G__PWFormatDictLN_reverse_iteratorlEvectorlEPWSegmentcOallocatorlEPWSegmentgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PWFormatDictLN_vectorlEPWFragmentcOallocatorlEPWFragmentgRsPgR;
extern G__linked_taginfo G__PWFormatDictLN_vectorlEPWFragmentcOallocatorlEPWFragmentgRsPgRcLcLiterator;
extern G__linked_taginfo G__PWFormatDictLN_reverse_iteratorlEvectorlEPWFragmentcOallocatorlEPWFragmentgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<PWSegment,allocator<PWSegment> > G__vectorlEPWSegmentcOallocatorlEPWSegmentgRsPgR;
typedef vector<PWFragment,allocator<PWFragment> > G__vectorlEPWFragmentcOallocatorlEPWFragmentgRsPgR;
