/********************************************************************
* G2FormatDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G2FormatDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG2FormatDict();
extern void G__cpp_setup_inheritanceG2FormatDict();
extern void G__cpp_setup_typetableG2FormatDict();
extern void G__cpp_setup_memvarG2FormatDict();
extern void G__cpp_setup_globalG2FormatDict();
extern void G__cpp_setup_memfuncG2FormatDict();
extern void G__cpp_setup_funcG2FormatDict();
extern void G__set_cpp_environmentG2FormatDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/G2Segment.h"
#include "/user/benderp/Programs/GRETINA/include/G2Fragment.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G2FormatDictLN_TClass;
extern G__linked_taginfo G__G2FormatDictLN_TBuffer;
extern G__linked_taginfo G__G2FormatDictLN_TMemberInspector;
extern G__linked_taginfo G__G2FormatDictLN_TObject;
extern G__linked_taginfo G__G2FormatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G2FormatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G2FormatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G2FormatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G2FormatDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G2FormatDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G2FormatDictLN_TVector3;
extern G__linked_taginfo G__G2FormatDictLN_TGEBEvent;
extern G__linked_taginfo G__G2FormatDictLN_TGEBEventcLcLTGEBGeSegType1;
extern G__linked_taginfo G__G2FormatDictLN_TGEBEventcLcLTGEBBankType1;
extern G__linked_taginfo G__G2FormatDictLN_G2Segment;
extern G__linked_taginfo G__G2FormatDictLN_G2Fragment;
extern G__linked_taginfo G__G2FormatDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR;
extern G__linked_taginfo G__G2FormatDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiterator;
extern G__linked_taginfo G__G2FormatDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G2FormatDictLN_vectorlEG2FragmentcOallocatorlEG2FragmentgRsPgR;
extern G__linked_taginfo G__G2FormatDictLN_vectorlEG2FragmentcOallocatorlEG2FragmentgRsPgRcLcLiterator;
extern G__linked_taginfo G__G2FormatDictLN_reverse_iteratorlEvectorlEG2FragmentcOallocatorlEG2FragmentgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<G2Segment,allocator<G2Segment> > G__vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR;
typedef vector<G2Fragment,allocator<G2Fragment> > G__vectorlEG2FragmentcOallocatorlEG2FragmentgRsPgR;
