//
// File generated by rootcint at Mon May 25 18:42:12 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TLaBrDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TLaBrDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TLaBrHit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TLaBrHit(void *p = 0);
   static void *newArray_TLaBrHit(Long_t size, void *p);
   static void delete_TLaBrHit(void *p);
   static void deleteArray_TLaBrHit(void *p);
   static void destruct_TLaBrHit(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TLaBrHit*)
   {
      ::TLaBrHit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TLaBrHit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TLaBrHit", ::TLaBrHit::Class_Version(), "/global/home/users/gretina/bender/GRETINA/include/TLaBrHit.h", 14,
                  typeid(::TLaBrHit), DefineBehavior(ptr, ptr),
                  &::TLaBrHit::Dictionary, isa_proxy, 4,
                  sizeof(::TLaBrHit) );
      instance.SetNew(&new_TLaBrHit);
      instance.SetNewArray(&newArray_TLaBrHit);
      instance.SetDelete(&delete_TLaBrHit);
      instance.SetDeleteArray(&deleteArray_TLaBrHit);
      instance.SetDestructor(&destruct_TLaBrHit);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TLaBrHit*)
   {
      return GenerateInitInstanceLocal((::TLaBrHit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TLaBrHit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TLaBr_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TLaBr(void *p = 0);
   static void *newArray_TLaBr(Long_t size, void *p);
   static void delete_TLaBr(void *p);
   static void deleteArray_TLaBr(void *p);
   static void destruct_TLaBr(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TLaBr*)
   {
      ::TLaBr *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TLaBr >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TLaBr", ::TLaBr::Class_Version(), "/global/home/users/gretina/bender/GRETINA/include/TLaBr.h", 12,
                  typeid(::TLaBr), DefineBehavior(ptr, ptr),
                  &::TLaBr::Dictionary, isa_proxy, 4,
                  sizeof(::TLaBr) );
      instance.SetNew(&new_TLaBr);
      instance.SetNewArray(&newArray_TLaBr);
      instance.SetDelete(&delete_TLaBr);
      instance.SetDeleteArray(&deleteArray_TLaBr);
      instance.SetDestructor(&destruct_TLaBr);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TLaBr*)
   {
      return GenerateInitInstanceLocal((::TLaBr*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TLaBr*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TLaBrHit::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TLaBrHit::Class_Name()
{
   return "TLaBrHit";
}

//______________________________________________________________________________
const char *TLaBrHit::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TLaBrHit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TLaBrHit::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TLaBrHit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TLaBrHit::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TLaBrHit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TLaBrHit::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TLaBrHit*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TLaBr::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TLaBr::Class_Name()
{
   return "TLaBr";
}

//______________________________________________________________________________
const char *TLaBr::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TLaBr*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TLaBr::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TLaBr*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TLaBr::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TLaBr*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TLaBr::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TLaBr*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TLaBrHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class TLaBrHit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TLaBrHit::Class(),this);
   } else {
      R__b.WriteClassBuffer(TLaBrHit::Class(),this);
   }
}

//______________________________________________________________________________
void TLaBrHit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TLaBrHit.
      TClass *R__cl = ::TLaBrHit::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTimeStamp", &fTimeStamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRefTdc", &fRefTdc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTdc", &fTdc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fId", &fId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEnergy", &fEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCharge", &fCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosition", &fPosition);
      R__insp.InspectMember(fPosition, "fPosition.");
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TLaBrHit(void *p) {
      return  p ? new(p) ::TLaBrHit : new ::TLaBrHit;
   }
   static void *newArray_TLaBrHit(Long_t nElements, void *p) {
      return p ? new(p) ::TLaBrHit[nElements] : new ::TLaBrHit[nElements];
   }
   // Wrapper around operator delete
   static void delete_TLaBrHit(void *p) {
      delete ((::TLaBrHit*)p);
   }
   static void deleteArray_TLaBrHit(void *p) {
      delete [] ((::TLaBrHit*)p);
   }
   static void destruct_TLaBrHit(void *p) {
      typedef ::TLaBrHit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TLaBrHit

//______________________________________________________________________________
void TLaBr::Streamer(TBuffer &R__b)
{
   // Stream an object of class TLaBr.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TLaBr::Class(),this);
   } else {
      R__b.WriteClassBuffer(TLaBr::Class(),this);
   }
}

//______________________________________________________________________________
void TLaBr::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TLaBr.
      TClass *R__cl = ::TLaBr::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "labr_hits", (void*)&labr_hits);
      R__insp.InspectMember("vector<TLaBrHit>", (void*)&labr_hits, "labr_hits.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TLaBr(void *p) {
      return  p ? new(p) ::TLaBr : new ::TLaBr;
   }
   static void *newArray_TLaBr(Long_t nElements, void *p) {
      return p ? new(p) ::TLaBr[nElements] : new ::TLaBr[nElements];
   }
   // Wrapper around operator delete
   static void delete_TLaBr(void *p) {
      delete ((::TLaBr*)p);
   }
   static void deleteArray_TLaBr(void *p) {
      delete [] ((::TLaBr*)p);
   }
   static void destruct_TLaBr(void *p) {
      typedef ::TLaBr current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TLaBr

namespace ROOT {
   void vectorlETLaBrHitgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlETLaBrHitgR_Dictionary();
   static void *new_vectorlETLaBrHitgR(void *p = 0);
   static void *newArray_vectorlETLaBrHitgR(Long_t size, void *p);
   static void delete_vectorlETLaBrHitgR(void *p);
   static void deleteArray_vectorlETLaBrHitgR(void *p);
   static void destruct_vectorlETLaBrHitgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<TLaBrHit>*)
   {
      vector<TLaBrHit> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TLaBrHit>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<TLaBrHit>", -2, "/usr/local/lib/root/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<TLaBrHit>), DefineBehavior(ptr, ptr),
                  0, &vectorlETLaBrHitgR_Dictionary, isa_proxy, 4,
                  sizeof(vector<TLaBrHit>) );
      instance.SetNew(&new_vectorlETLaBrHitgR);
      instance.SetNewArray(&newArray_vectorlETLaBrHitgR);
      instance.SetDelete(&delete_vectorlETLaBrHitgR);
      instance.SetDeleteArray(&deleteArray_vectorlETLaBrHitgR);
      instance.SetDestructor(&destruct_vectorlETLaBrHitgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TLaBrHit> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<TLaBrHit>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlETLaBrHitgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<TLaBrHit>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlETLaBrHitgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TLaBrHit> : new vector<TLaBrHit>;
   }
   static void *newArray_vectorlETLaBrHitgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TLaBrHit>[nElements] : new vector<TLaBrHit>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlETLaBrHitgR(void *p) {
      delete ((vector<TLaBrHit>*)p);
   }
   static void deleteArray_vectorlETLaBrHitgR(void *p) {
      delete [] ((vector<TLaBrHit>*)p);
   }
   static void destruct_vectorlETLaBrHitgR(void *p) {
      typedef vector<TLaBrHit> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<TLaBrHit>

/********************************************************
* TLaBrDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTLaBrDict();

extern "C" void G__set_cpp_environmentTLaBrDict() {
  G__cpp_reset_tagtableTLaBrDict();
}
#include <new>
extern "C" int G__cpp_dllrevTLaBrDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TLaBrHit */
static int G__TLaBrDict_236_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TLaBrHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TLaBrHit[n];
     } else {
       p = new((void*) gvp) TLaBrHit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TLaBrHit;
     } else {
       p = new((void*) gvp) TLaBrHit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TLaBrHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TLaBrHit(*(LaBrSegment*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) TLaBrHit(*(LaBrSegment*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TLaBrHit*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TLaBrHit*) G__getstructoffset())->GetCrystalId());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TLaBrHit*) G__getstructoffset())->GetTDC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TLaBrHit*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TLaBrHit*) G__getstructoffset())->GetCharge());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TVector3& obj = ((TLaBrHit*) G__getstructoffset())->GetPosition();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TLaBrHit*) G__getstructoffset())->SetTimeStamp((const Long_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TLaBrHit*) G__getstructoffset())->SetTDCRef((const Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TLaBrHit*) G__getstructoffset())->IsValid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TLaBrHit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TLaBrHit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TLaBrHit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TLaBrHit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TLaBrHit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TLaBrHit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TLaBrHit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TLaBrHit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_236_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TLaBrHit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TLaBrDict_236_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TLaBrHit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TLaBrHit(*(TLaBrHit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TLaBrHit G__TTLaBrHit;
static int G__TLaBrDict_236_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TLaBrHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TLaBrHit*) (soff+(sizeof(TLaBrHit)*i)))->~G__TTLaBrHit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TLaBrHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TLaBrHit*) (soff))->~G__TTLaBrHit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TLaBrDict_236_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TLaBrHit* dest = (TLaBrHit*) G__getstructoffset();
   *dest = *(TLaBrHit*) libp->para[0].ref;
   const TLaBrHit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TLaBr */
static int G__TLaBrDict_237_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TLaBr* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TLaBr[n];
     } else {
       p = new((void*) gvp) TLaBr[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TLaBr;
     } else {
       p = new((void*) gvp) TLaBr;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TLaBr* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TLaBr(*(LaBrFragment*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) TLaBr(*(LaBrFragment*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TLaBr*) G__getstructoffset())->Set(*(LaBrFragment*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TLaBr*) G__getstructoffset())->AddLaBrHit(*(TLaBrHit*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TLaBr*) G__getstructoffset())->NumberOfHits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TLaBr*) G__getstructoffset())->GetHit(*(int*) G__Intref(&libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVector3* pobj;
         TVector3 xobj = TLaBr::FindPosition((int) G__int(libp->para[0]));
         pobj = new TVector3(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TLaBr::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TLaBr::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TLaBr::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TLaBr::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TLaBr*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TLaBr::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TLaBr::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TLaBr::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_237_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TLaBr::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TLaBrDict_237_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TLaBr* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TLaBr(*(TLaBr*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TLaBr G__TTLaBr;
static int G__TLaBrDict_237_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TLaBr*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TLaBr*) (soff+(sizeof(TLaBr)*i)))->~G__TTLaBr();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TLaBr*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TLaBr*) (soff))->~G__TTLaBr();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TLaBrDict_237_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TLaBr* dest = (TLaBr*) G__getstructoffset();
   *dest = *(TLaBr*) libp->para[0].ref;
   const TLaBr& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* vector<TLaBrHit,allocator<TLaBrHit> > */
static int G__TLaBrDict_239_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<TLaBrHit,allocator<TLaBrHit> >::reference obj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->at((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TLaBrHit,allocator<TLaBrHit> >::const_reference obj = ((const vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->at((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TLaBrHit,allocator<TLaBrHit> >::iterator* pobj;
         vector<TLaBrHit,allocator<TLaBrHit> >::iterator xobj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->begin();
         pobj = new vector<TLaBrHit,allocator<TLaBrHit> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TLaBrHit,allocator<TLaBrHit> >::iterator* pobj;
         vector<TLaBrHit,allocator<TLaBrHit> >::iterator xobj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->end();
         pobj = new vector<TLaBrHit,allocator<TLaBrHit> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator* pobj;
         vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator xobj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->rbegin();
         pobj = new vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator* pobj;
         vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator xobj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->rend();
         pobj = new vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->max_size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->resize((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->resize((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]), *((TLaBrHit*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->capacity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->empty());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<TLaBrHit,allocator<TLaBrHit> >::reference obj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->operator[]((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TLaBrHit,allocator<TLaBrHit> >::const_reference obj = ((const vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->operator[]((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<TLaBrHit,allocator<TLaBrHit> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<TLaBrHit,allocator<TLaBrHit> >[n];
     } else {
       p = new((void*) gvp) vector<TLaBrHit,allocator<TLaBrHit> >[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<TLaBrHit,allocator<TLaBrHit> >;
     } else {
       p = new((void*) gvp) vector<TLaBrHit,allocator<TLaBrHit> >;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<TLaBrHit,allocator<TLaBrHit> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<TLaBrHit,allocator<TLaBrHit> >((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]), *(TLaBrHit*) libp->para[1].ref);
     } else {
       p = new((void*) gvp) vector<TLaBrHit,allocator<TLaBrHit> >((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]), *(TLaBrHit*) libp->para[1].ref);
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<TLaBrHit,allocator<TLaBrHit> >((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) vector<TLaBrHit,allocator<TLaBrHit> >((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<TLaBrHit,allocator<TLaBrHit> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<TLaBrHit,allocator<TLaBrHit> >(*(vector<TLaBrHit,allocator<TLaBrHit> >*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) vector<TLaBrHit,allocator<TLaBrHit> >(*(vector<TLaBrHit,allocator<TLaBrHit> >*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<TLaBrHit,allocator<TLaBrHit> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<TLaBrHit,allocator<TLaBrHit> >(*((vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator*) G__int(libp->para[0])), *((vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator*) G__int(libp->para[1])));
   } else {
     p = new((void*) gvp) vector<TLaBrHit,allocator<TLaBrHit> >(*((vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator*) G__int(libp->para[0])), *((vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator*) G__int(libp->para[1])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<TLaBrHit,allocator<TLaBrHit> >& obj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->operator=(*(vector<TLaBrHit,allocator<TLaBrHit> >*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->reserve((vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TLaBrHit& obj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->front();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TLaBrHit& obj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->back();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->push_back(*(TLaBrHit*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->swap(*(vector<TLaBrHit,allocator<TLaBrHit> >*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TLaBrHit,allocator<TLaBrHit> >::iterator* pobj;
         vector<TLaBrHit,allocator<TLaBrHit> >::iterator xobj = ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->insert(*((vector<TLaBrHit,allocator<TLaBrHit> >::iterator*) G__int(libp->para[0])), *(TLaBrHit*) libp->para[1].ref);
         pobj = new vector<TLaBrHit,allocator<TLaBrHit> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->insert(*((vector<TLaBrHit,allocator<TLaBrHit> >::iterator*) G__int(libp->para[0])), *((vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator*) G__int(libp->para[1]))
, *((vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->insert(*((vector<TLaBrHit,allocator<TLaBrHit> >::iterator*) G__int(libp->para[0])), (vector<TLaBrHit,allocator<TLaBrHit> >::size_type) G__int(libp->para[1])
, *(TLaBrHit*) libp->para[2].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->pop_back();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->erase(*((vector<TLaBrHit,allocator<TLaBrHit> >::iterator*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->erase(*((vector<TLaBrHit,allocator<TLaBrHit> >::iterator*) G__int(libp->para[0])), *((vector<TLaBrHit,allocator<TLaBrHit> >::iterator*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TLaBrDict_239_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<TLaBrHit,allocator<TLaBrHit> >*) G__getstructoffset())->clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vector<TLaBrHit,allocator<TLaBrHit> > G__TvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR;
static int G__TLaBrDict_239_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vector<TLaBrHit,allocator<TLaBrHit> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vector<TLaBrHit,allocator<TLaBrHit> >*) (soff+(sizeof(vector<TLaBrHit,allocator<TLaBrHit> >)*i)))->~G__TvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vector<TLaBrHit,allocator<TLaBrHit> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vector<TLaBrHit,allocator<TLaBrHit> >*) (soff))->~G__TvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TLaBrHit */

/* TLaBr */

/* vector<TLaBrHit,allocator<TLaBrHit> > */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTLaBrDict {
 public:
  G__Sizep2memfuncTLaBrDict(): p(&G__Sizep2memfuncTLaBrDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTLaBrDict::*p)();
};

size_t G__get_sizep2memfuncTLaBrDict()
{
  G__Sizep2memfuncTLaBrDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTLaBrDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit))) {
     TLaBrHit *G__Lderived;
     G__Lderived=(TLaBrHit*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit),G__get_linked_tagnum(&G__TLaBrDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr))) {
     TLaBr *G__Lderived;
     G__Lderived=(TLaBr*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr),G__get_linked_tagnum(&G__TLaBrDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTLaBrDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<G2Segment>",117,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TLaBrDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLaBrHit>",117,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("value_type",117,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pointer",85,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit),256,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reference",117,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit),1,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reference",117,G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit),257,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TLaBrHit */
static void G__setup_memvarTLaBrHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit));
   { TLaBrHit *p; p=(TLaBrHit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("Long_t"),-1,4,"fTimeStamp=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fRefTdc=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fTdc=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fId=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fCharge=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TLaBrDictLN_TVector3),-1,-1,4,"fPosition=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TLaBrDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TLaBr */
static void G__setup_memvarTLaBr(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr));
   { TLaBr *p; p=(TLaBr*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR),G__defined_typename("vector<TLaBrHit>"),-1,4,"labr_hits=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TLaBrDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* vector<TLaBrHit,allocator<TLaBrHit> > */
static void G__setup_memvarvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   { vector<TLaBrHit,allocator<TLaBrHit> > *p; p=(vector<TLaBrHit,allocator<TLaBrHit> >*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTLaBrDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTLaBrHit(void) {
   /* TLaBrHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit));
   G__memfunc_setup("TLaBrHit",730,G__TLaBrDict_236_0_1, 105, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TLaBrHit",730,G__TLaBrDict_236_0_2, 105, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), -1, 0, 1, 1, 1, 0, "u 'LaBrSegment' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__TLaBrDict_236_0_3, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCrystalId",1199,G__TLaBrDict_236_0_4, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTDC",507,G__TLaBrDict_236_0_5, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__TLaBrDict_236_0_6, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCharge",874,G__TLaBrDict_236_0_7, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPosition",1141,G__TLaBrDict_236_0_10, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TVector3), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimeStamp",1216,G__TLaBrDict_236_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "l - 'Long_t' 10 - ts", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTDCRef",804,G__TLaBrDict_236_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 10 - tdc_ref", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsValid",684,G__TLaBrDict_236_0_13, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TLaBrDict_236_0_14, 85, G__get_linked_tagnum(&G__TLaBrDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TLaBrHit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TLaBrDict_236_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TLaBrHit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TLaBrDict_236_0_16, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TLaBrHit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TLaBrDict_236_0_17, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TLaBrHit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TLaBrDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TLaBrDict_236_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TLaBrDict_236_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TLaBrHit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TLaBrDict_236_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TLaBrHit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TLaBrDict_236_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TLaBrHit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TLaBrDict_236_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TLaBrHit::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TLaBrHit", 730, G__TLaBrDict_236_0_26, (int) ('i'), G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), -1, 0, 1, 1, 1, 0, "u 'TLaBrHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TLaBrHit", 856, G__TLaBrDict_236_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TLaBrDict_236_0_28, (int) ('u'), G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), -1, 1, 1, 1, 1, 0, "u 'TLaBrHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTLaBr(void) {
   /* TLaBr */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr));
   G__memfunc_setup("TLaBr",437,G__TLaBrDict_237_0_1, 105, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TLaBr",437,G__TLaBrDict_237_0_2, 105, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr), -1, 0, 1, 1, 1, 0, "u 'LaBrFragment' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Set",300,G__TLaBrDict_237_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'LaBrFragment' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddLaBrHit",911,G__TLaBrDict_237_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TLaBrHit' - 1 - hit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NumberOfHits",1206,G__TLaBrDict_237_0_5, 105, -1, -1, 0, 0, 1, 1, 1, "", "LaBrHits.size(); }", (void*) NULL, 0);
   G__memfunc_setup("GetHit",581,G__TLaBrDict_237_0_6, 85, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), -1, 0, 1, 1, 1, 0, "i - - 11 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FindPosition",1238,G__TLaBrDict_237_0_9, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TVector3), -1, 0, 1, 3, 1, 0, "i - - 0 - cryId", (char*)NULL, (void*) G__func2void( (TVector3 (*)(int))(&TLaBr::FindPosition) ), 0);
   G__memfunc_setup("Class",502,G__TLaBrDict_237_0_10, 85, G__get_linked_tagnum(&G__TLaBrDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TLaBr::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TLaBrDict_237_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TLaBr::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TLaBrDict_237_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TLaBr::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TLaBrDict_237_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TLaBr::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TLaBrDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TLaBrDict_237_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TLaBrDict_237_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TLaBr::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TLaBrDict_237_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TLaBr::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TLaBrDict_237_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TLaBr::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TLaBrDict_237_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TLaBr::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TLaBr", 437, G__TLaBrDict_237_0_22, (int) ('i'), G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr), -1, 0, 1, 1, 1, 0, "u 'TLaBr' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TLaBr", 563, G__TLaBrDict_237_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TLaBrDict_237_0_24, (int) ('u'), G__get_linked_tagnum(&G__TLaBrDictLN_TLaBr), -1, 1, 1, 1, 1, 0, "u 'TLaBr' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR(void) {
   /* vector<TLaBrHit,allocator<TLaBrHit> > */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR));
   G__memfunc_setup("at",213,G__TLaBrDict_239_0_1, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("at",213,G__TLaBrDict_239_0_2, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("begin",517,G__TLaBrDict_239_0_3, 117, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("end",311,G__TLaBrDict_239_0_4, 117, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rbegin",631,G__TLaBrDict_239_0_5, 117, G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR), G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rend",425,G__TLaBrDict_239_0_6, 117, G__get_linked_tagnum(&G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR), G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__TLaBrDict_239_0_7, 107, -1, G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("max_size",864,G__TLaBrDict_239_0_8, 107, -1, G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__TLaBrDict_239_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__TLaBrDict_239_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - sz u 'TLaBrHit' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("capacity",846,G__TLaBrDict_239_0_11, 107, -1, G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("empty",559,G__TLaBrDict_239_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__TLaBrDict_239_0_13, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__TLaBrDict_239_0_14, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), G__defined_typename("vector<TLaBrHit,allocator<TLaBrHit> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<TLaBrHit,allocator<TLaBrHit> >",3400,G__TLaBrDict_239_0_15, 105, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<TLaBrHit,allocator<TLaBrHit> >",3400,G__TLaBrDict_239_0_16, 105, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR), -1, 0, 2, 1, 1, 0, 
"k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - n u 'TLaBrHit' - 11 'TLaBrHit()' value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<TLaBrHit,allocator<TLaBrHit> >",3400,G__TLaBrDict_239_0_17, 105, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<TLaBrHit,allocator<TLaBrHit> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<TLaBrHit,allocator<TLaBrHit> >",3400,G__TLaBrDict_239_0_18, 105, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR), -1, 0, 2, 1, 1, 0, 
"u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' 'vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator' 10 - first u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' 'vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__TLaBrDict_239_0_19, 117, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<TLaBrHit,allocator<TLaBrHit> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("reserve",764,G__TLaBrDict_239_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("front",553,G__TLaBrDict_239_0_21, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("back",401,G__TLaBrDict_239_0_22, 117, G__get_linked_tagnum(&G__TLaBrDictLN_TLaBrHit), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("push_back",944,G__TLaBrDict_239_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TLaBrHit' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("swap",443,G__TLaBrDict_239_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TLaBrHit,allocator<TLaBrHit> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__TLaBrDict_239_0_25, 117, G__get_linked_tagnum(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0, 
"u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' - 0 - position u 'TLaBrHit' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__TLaBrDict_239_0_26, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' - 0 - position u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' 'vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator' 10 - first "
"u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' 'vector<TLaBrHit,allocator<TLaBrHit> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__TLaBrDict_239_0_27, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' - 0 - position k - 'vector<TLaBrHit,allocator<TLaBrHit> >::size_type' 0 - n "
"u 'TLaBrHit' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("pop_back",831,G__TLaBrDict_239_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__TLaBrDict_239_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__TLaBrDict_239_0_30, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' - 0 - first u 'vector<TLaBrHit,allocator<TLaBrHit> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clear",519,G__TLaBrDict_239_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vector<TLaBrHit,allocator<TLaBrHit> >", 3526, G__TLaBrDict_239_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTLaBrDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTLaBrDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTLaBrDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TLaBrDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR = { "vector<G2Segment,allocator<G2Segment> >" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<G2Segment,allocator<G2Segment> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_LaBrFragment = { "LaBrFragment" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_LaBrSegment = { "LaBrSegment" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TLaBrHit = { "TLaBrHit" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_TLaBr = { "TLaBr" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR = { "vector<TLaBrHit,allocator<TLaBrHit> >" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator = { "vector<TLaBrHit,allocator<TLaBrHit> >::iterator" , 99 , -1 };
G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLaBrHit,allocator<TLaBrHit> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTLaBrDict() {
  G__TLaBrDictLN_TClass.tagnum = -1 ;
  G__TLaBrDictLN_TBuffer.tagnum = -1 ;
  G__TLaBrDictLN_TMemberInspector.tagnum = -1 ;
  G__TLaBrDictLN_TObject.tagnum = -1 ;
  G__TLaBrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TLaBrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TLaBrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TLaBrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TLaBrDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR.tagnum = -1 ;
  G__TLaBrDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TLaBrDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TLaBrDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TLaBrDictLN_TVector3.tagnum = -1 ;
  G__TLaBrDictLN_LaBrFragment.tagnum = -1 ;
  G__TLaBrDictLN_LaBrSegment.tagnum = -1 ;
  G__TLaBrDictLN_TLaBrHit.tagnum = -1 ;
  G__TLaBrDictLN_TLaBr.tagnum = -1 ;
  G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR.tagnum = -1 ;
  G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator.tagnum = -1 ;
  G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTLaBrDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_LaBrFragment);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_LaBrSegment);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TLaBrHit),sizeof(TLaBrHit),-1,324864,(char*)NULL,G__setup_memvarTLaBrHit,G__setup_memfuncTLaBrHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TLaBrDictLN_TLaBr),sizeof(TLaBr),-1,324864,(char*)NULL,G__setup_memvarTLaBr,G__setup_memfuncTLaBr);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR),sizeof(vector<TLaBrHit,allocator<TLaBrHit> >),-1,298752,(char*)NULL,G__setup_memvarvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR,G__setup_memfuncvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupTLaBrDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTLaBrDict()");
  G__set_cpp_environmentTLaBrDict();
  G__cpp_setup_tagtableTLaBrDict();

  G__cpp_setup_inheritanceTLaBrDict();

  G__cpp_setup_typetableTLaBrDict();

  G__cpp_setup_memvarTLaBrDict();

  G__cpp_setup_memfuncTLaBrDict();
  G__cpp_setup_globalTLaBrDict();
  G__cpp_setup_funcTLaBrDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTLaBrDict();
  return;
}
class G__cpp_setup_initTLaBrDict {
  public:
    G__cpp_setup_initTLaBrDict() { G__add_setup_func("TLaBrDict",(G__incsetup)(&G__cpp_setupTLaBrDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTLaBrDict() { G__remove_setup_func("TLaBrDict"); }
};
G__cpp_setup_initTLaBrDict G__cpp_setup_initializerTLaBrDict;

