/********************************************************************
* TLaBrDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TLaBrDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTLaBrDict();
extern void G__cpp_setup_inheritanceTLaBrDict();
extern void G__cpp_setup_typetableTLaBrDict();
extern void G__cpp_setup_memvarTLaBrDict();
extern void G__cpp_setup_globalTLaBrDict();
extern void G__cpp_setup_memfuncTLaBrDict();
extern void G__cpp_setup_funcTLaBrDict();
extern void G__set_cpp_environmentTLaBrDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/global/home/users/gretina/bender/GRETINA/include/TLaBr.h"
#include "/global/home/users/gretina/bender/GRETINA/include/TLaBrHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TLaBrDictLN_TClass;
extern G__linked_taginfo G__TLaBrDictLN_TBuffer;
extern G__linked_taginfo G__TLaBrDictLN_TMemberInspector;
extern G__linked_taginfo G__TLaBrDictLN_TObject;
extern G__linked_taginfo G__TLaBrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TLaBrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TLaBrDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR;
extern G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TLaBrDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TLaBrDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TLaBrDictLN_TVector3;
extern G__linked_taginfo G__TLaBrDictLN_LaBrFragment;
extern G__linked_taginfo G__TLaBrDictLN_LaBrSegment;
extern G__linked_taginfo G__TLaBrDictLN_TLaBrHit;
extern G__linked_taginfo G__TLaBrDictLN_TLaBr;
extern G__linked_taginfo G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR;
extern G__linked_taginfo G__TLaBrDictLN_vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__TLaBrDictLN_reverse_iteratorlEvectorlETLaBrHitcOallocatorlETLaBrHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<TLaBrHit,allocator<TLaBrHit> > G__vectorlETLaBrHitcOallocatorlETLaBrHitgRsPgR;
