/********************************************************************
* TGEBFormatDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGEBFormatDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGEBFormatDict();
extern void G__cpp_setup_inheritanceTGEBFormatDict();
extern void G__cpp_setup_typetableTGEBFormatDict();
extern void G__cpp_setup_memvarTGEBFormatDict();
extern void G__cpp_setup_globalTGEBFormatDict();
extern void G__cpp_setup_memfuncTGEBFormatDict();
extern void G__cpp_setup_funcTGEBFormatDict();
extern void G__set_cpp_environmentTGEBFormatDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/TGEBFile.h"
#include "/user/benderp/Programs/GRETINA/include/TGEBMultiFile.h"
#include "/user/benderp/Programs/GRETINA/include/TGEBEvent.h"
#include "/user/benderp/Programs/GRETINA/include/TGEBEventHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGEBFormatDictLN_TClass;
extern G__linked_taginfo G__TGEBFormatDictLN_TBuffer;
extern G__linked_taginfo G__TGEBFormatDictLN_TMemberInspector;
extern G__linked_taginfo G__TGEBFormatDictLN_TObject;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_string;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEvent;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBFile;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEventHeader;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEventcLcLTGEBGeSegType1;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEventcLcLTGEBBankType1;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEventcLcLTPWHit;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEventcLcLTPWBank;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEventcLcLTLaBrSeg;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBEventcLcLTLaBrBank;
extern G__linked_taginfo G__TGEBFormatDictLN_TGEBMultiFile;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlETGEBEventmUcOallocatorlETGEBEventmUgRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_reverse_iteratorlEvectorlETGEBEventmUcOallocatorlETGEBEventmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlETGEBFilemUcOallocatorlETGEBFilemUgRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_reverse_iteratorlEvectorlETGEBFilemUcOallocatorlETGEBFilemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGEBFormatDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGEBFormatDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
