/********************************************************************
* LaBrFormatDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LaBrFormatDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLaBrFormatDict();
extern void G__cpp_setup_inheritanceLaBrFormatDict();
extern void G__cpp_setup_typetableLaBrFormatDict();
extern void G__cpp_setup_memvarLaBrFormatDict();
extern void G__cpp_setup_globalLaBrFormatDict();
extern void G__cpp_setup_memfuncLaBrFormatDict();
extern void G__cpp_setup_funcLaBrFormatDict();
extern void G__set_cpp_environmentLaBrFormatDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/global/home/users/gretina/bender/GRETINA/include/LaBrSegment.h"
#include "/global/home/users/gretina/bender/GRETINA/include/LaBrFragment.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LaBrFormatDictLN_TClass;
extern G__linked_taginfo G__LaBrFormatDictLN_TBuffer;
extern G__linked_taginfo G__LaBrFormatDictLN_TMemberInspector;
extern G__linked_taginfo G__LaBrFormatDictLN_TObject;
extern G__linked_taginfo G__LaBrFormatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LaBrFormatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LaBrFormatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LaBrFormatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LaBrFormatDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LaBrFormatDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__LaBrFormatDictLN_TVector3;
extern G__linked_taginfo G__LaBrFormatDictLN_TGEBEvent;
extern G__linked_taginfo G__LaBrFormatDictLN_TGEBEventcLcLTLaBrSeg;
extern G__linked_taginfo G__LaBrFormatDictLN_LaBrSegment;
extern G__linked_taginfo G__LaBrFormatDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__LaBrFormatDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__LaBrFormatDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__LaBrFormatDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LaBrFormatDictLN_LaBrFragment;
extern G__linked_taginfo G__LaBrFormatDictLN_vectorlELaBrSegmentcOallocatorlELaBrSegmentgRsPgR;
extern G__linked_taginfo G__LaBrFormatDictLN_vectorlELaBrSegmentcOallocatorlELaBrSegmentgRsPgRcLcLiterator;
extern G__linked_taginfo G__LaBrFormatDictLN_reverse_iteratorlEvectorlELaBrSegmentcOallocatorlELaBrSegmentgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LaBrFormatDictLN_vectorlELaBrFragmentcOallocatorlELaBrFragmentgRsPgR;
extern G__linked_taginfo G__LaBrFormatDictLN_vectorlELaBrFragmentcOallocatorlELaBrFragmentgRsPgRcLcLiterator;
extern G__linked_taginfo G__LaBrFormatDictLN_reverse_iteratorlEvectorlELaBrFragmentcOallocatorlELaBrFragmentgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<LaBrSegment,allocator<LaBrSegment> > G__vectorlELaBrSegmentcOallocatorlELaBrSegmentgRsPgR;
typedef vector<LaBrFragment,allocator<LaBrFragment> > G__vectorlELaBrFragmentcOallocatorlELaBrFragmentgRsPgR;
