/********************************************************************
* TGRUTOptionsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRUTOptionsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRUTOptionsDict();
extern void G__cpp_setup_inheritanceTGRUTOptionsDict();
extern void G__cpp_setup_typetableTGRUTOptionsDict();
extern void G__cpp_setup_memvarTGRUTOptionsDict();
extern void G__cpp_setup_globalTGRUTOptionsDict();
extern void G__cpp_setup_memfuncTGRUTOptionsDict();
extern void G__cpp_setup_funcTGRUTOptionsDict();
extern void G__set_cpp_environmentTGRUTOptionsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/TGRUTOptions.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRUTOptionsDictLN_string;
extern G__linked_taginfo G__TGRUTOptionsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRUTOptionsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRUTOptionsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRUTOptionsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRUTOptionsDictLN_TGRUTOptions;
extern G__linked_taginfo G__TGRUTOptionsDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TGRUTOptionsDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
