/********************************************************************
* TGRUTintDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRUTintDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRUTintDict();
extern void G__cpp_setup_inheritanceTGRUTintDict();
extern void G__cpp_setup_typetableTGRUTintDict();
extern void G__cpp_setup_memvarTGRUTintDict();
extern void G__cpp_setup_globalTGRUTintDict();
extern void G__cpp_setup_memfuncTGRUTintDict();
extern void G__cpp_setup_funcTGRUTintDict();
extern void G__set_cpp_environmentTGRUTintDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/TGRUTint.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRUTintDictLN_TClass;
extern G__linked_taginfo G__TGRUTintDictLN_TBuffer;
extern G__linked_taginfo G__TGRUTintDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRUTintDictLN_TObject;
extern G__linked_taginfo G__TGRUTintDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGRUTintDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TGRUTintDictLN_string;
extern G__linked_taginfo G__TGRUTintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRUTintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRUTintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRUTintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRUTintDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TGRUTintDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRUTintDictLN_TQObject;
extern G__linked_taginfo G__TGRUTintDictLN_TApplication;
extern G__linked_taginfo G__TGRUTintDictLN_TRint;
extern G__linked_taginfo G__TGRUTintDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRUTintDictLN_TEnv;
extern G__linked_taginfo G__TGRUTintDictLN_TGRUTint;

/* STUB derived class for protected member access */
