/********************************************************************
* TPhosWallDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TPhosWallDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTPhosWallDict();
extern void G__cpp_setup_inheritanceTPhosWallDict();
extern void G__cpp_setup_typetableTPhosWallDict();
extern void G__cpp_setup_memvarTPhosWallDict();
extern void G__cpp_setup_globalTPhosWallDict();
extern void G__cpp_setup_memfuncTPhosWallDict();
extern void G__cpp_setup_funcTPhosWallDict();
extern void G__set_cpp_environmentTPhosWallDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/TPhosWall.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPhosWallDictLN_TClass;
extern G__linked_taginfo G__TPhosWallDictLN_TBuffer;
extern G__linked_taginfo G__TPhosWallDictLN_TMemberInspector;
extern G__linked_taginfo G__TPhosWallDictLN_TObject;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TPhosWallDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TPhosWallDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TPhosWallDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TPhosWallDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TPhosWallDictLN_TVector3;
extern G__linked_taginfo G__TPhosWallDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TPhosWallDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhosWallDictLN_PWFragment;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlEPWSegmentcOallocatorlEPWSegmentgRsPgR;
extern G__linked_taginfo G__TPhosWallDictLN_reverse_iteratorlEvectorlEPWSegmentcOallocatorlEPWSegmentgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhosWallDictLN_TPhosWall;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__TPhosWallDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlEPWFragmentcOallocatorlEPWFragmentgRsPgR;
extern G__linked_taginfo G__TPhosWallDictLN_vectorlEPWFragmentcOallocatorlEPWFragmentgRsPgRcLcLiterator;
extern G__linked_taginfo G__TPhosWallDictLN_reverse_iteratorlEvectorlEPWFragmentcOallocatorlEPWFragmentgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<PWFragment,allocator<PWFragment> > G__vectorlEPWFragmentcOallocatorlEPWFragmentgRsPgR;
