/********************************************************************
* TGretinaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGretinaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGretinaDict();
extern void G__cpp_setup_inheritanceTGretinaDict();
extern void G__cpp_setup_typetableTGretinaDict();
extern void G__cpp_setup_memvarTGretinaDict();
extern void G__cpp_setup_globalTGretinaDict();
extern void G__cpp_setup_memfuncTGretinaDict();
extern void G__cpp_setup_funcTGretinaDict();
extern void G__set_cpp_environmentTGretinaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/TGretina.h"
#include "/user/benderp/Programs/GRETINA/include/TGretinaHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGretinaDictLN_TClass;
extern G__linked_taginfo G__TGretinaDictLN_TBuffer;
extern G__linked_taginfo G__TGretinaDictLN_TMemberInspector;
extern G__linked_taginfo G__TGretinaDictLN_TObject;
extern G__linked_taginfo G__TGretinaDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__TGretinaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGretinaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGretinaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGretinaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGretinaDictLN_G2Fragment;
extern G__linked_taginfo G__TGretinaDictLN_vectorlEG2SegmentcOallocatorlEG2SegmentgRsPgR;
extern G__linked_taginfo G__TGretinaDictLN_reverse_iteratorlEvectorlEG2SegmentcOallocatorlEG2SegmentgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGretinaDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGretinaDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGretinaDictLN_TVector3;
extern G__linked_taginfo G__TGretinaDictLN_TGretinaHit;
extern G__linked_taginfo G__TGretinaDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGretinaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGretinaDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__TGretinaDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGretinaDictLN_TGretina;
extern G__linked_taginfo G__TGretinaDictLN_vectorlETGretinaHitcOallocatorlETGretinaHitgRsPgR;
extern G__linked_taginfo G__TGretinaDictLN_vectorlETGretinaHitcOallocatorlETGretinaHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__TGretinaDictLN_reverse_iteratorlEvectorlETGretinaHitcOallocatorlETGretinaHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<TGretinaHit,allocator<TGretinaHit> > G__vectorlETGretinaHitcOallocatorlETGretinaHitgRsPgR;
