/********************************************************************
* GROOTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GROOTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGROOTDict();
extern void G__cpp_setup_inheritanceGROOTDict();
extern void G__cpp_setup_typetableGROOTDict();
extern void G__cpp_setup_memvarGROOTDict();
extern void G__cpp_setup_globalGROOTDict();
extern void G__cpp_setup_memfuncGROOTDict();
extern void G__cpp_setup_funcGROOTDict();
extern void G__set_cpp_environmentGROOTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/user/benderp/Programs/GRETINA/include/GROOTGuiFactory.h"
#include "/user/benderp/Programs/GRETINA/include/GRootCanvas.h"
#include "/user/benderp/Programs/GRETINA/include/GRootBrowser.h"
#include "/user/benderp/Programs/GRETINA/include/GCanvas.h"
#include "/user/benderp/Programs/GRETINA/include/GH1D.h"
#include "/user/benderp/Programs/GRETINA/include/GFile.h"
#include "/user/benderp/Programs/GRETINA/include/GTree.h"
#include "/user/benderp/Programs/GRETINA/include/GChain.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GROOTDictLN_TClass;
extern G__linked_taginfo G__GROOTDictLN_TBuffer;
extern G__linked_taginfo G__GROOTDictLN_TDirectory;
extern G__linked_taginfo G__GROOTDictLN_TMemberInspector;
extern G__linked_taginfo G__GROOTDictLN_TObject;
extern G__linked_taginfo G__GROOTDictLN_TNamed;
extern G__linked_taginfo G__GROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GROOTDictLN_TList;
extern G__linked_taginfo G__GROOTDictLN_TBrowser;
extern G__linked_taginfo G__GROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GROOTDictLN_TApplicationImp;
extern G__linked_taginfo G__GROOTDictLN_TCanvasImp;
extern G__linked_taginfo G__GROOTDictLN_TCanvas;
extern G__linked_taginfo G__GROOTDictLN_TBrowserImp;
extern G__linked_taginfo G__GROOTDictLN_TContextMenuImp;
extern G__linked_taginfo G__GROOTDictLN_TContextMenu;
extern G__linked_taginfo G__GROOTDictLN_TControlBarImp;
extern G__linked_taginfo G__GROOTDictLN_TControlBar;
extern G__linked_taginfo G__GROOTDictLN_TGuiFactory;
extern G__linked_taginfo G__GROOTDictLN_GROOTGuiFactory;
extern G__linked_taginfo G__GROOTDictLN_Event_t;
extern G__linked_taginfo G__GROOTDictLN_TGObject;
extern G__linked_taginfo G__GROOTDictLN_TQObject;
extern G__linked_taginfo G__GROOTDictLN_TGWindow;
extern G__linked_taginfo G__GROOTDictLN_TGPicture;
extern G__linked_taginfo G__GROOTDictLN_TAttLine;
extern G__linked_taginfo G__GROOTDictLN_TAttFill;
extern G__linked_taginfo G__GROOTDictLN_TAttMarker;
extern G__linked_taginfo G__GROOTDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GROOTDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GROOTDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GROOTDictLN_TGFrame;
extern G__linked_taginfo G__GROOTDictLN_TGCompositeFrame;
extern G__linked_taginfo G__GROOTDictLN_TGLayoutHints;
extern G__linked_taginfo G__GROOTDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GROOTDictLN_TDNDData;
extern G__linked_taginfo G__GROOTDictLN_TGVerticalFrame;
extern G__linked_taginfo G__GROOTDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__GROOTDictLN_TGMainFrame;
extern G__linked_taginfo G__GROOTDictLN_TGCanvas;
extern G__linked_taginfo G__GROOTDictLN_TGMenuBar;
extern G__linked_taginfo G__GROOTDictLN_TGPopupMenu;
extern G__linked_taginfo G__GROOTDictLN_TGStatusBar;
extern G__linked_taginfo G__GROOTDictLN_GRootContainer;
extern G__linked_taginfo G__GROOTDictLN_TGToolBar;
extern G__linked_taginfo G__GROOTDictLN_TGHorizontal3DLine;
extern G__linked_taginfo G__GROOTDictLN_TGVertical3DLine;
extern G__linked_taginfo G__GROOTDictLN_TVirtualPadEditor;
extern G__linked_taginfo G__GROOTDictLN_TGDockableFrame;
extern G__linked_taginfo G__GROOTDictLN_TGToolTip;
extern G__linked_taginfo G__GROOTDictLN_GCanvas;
extern G__linked_taginfo G__GROOTDictLN_GRootCanvas;
extern G__linked_taginfo G__GROOTDictLN_TGTab;
extern G__linked_taginfo G__GROOTDictLN_TGVSplitter;
extern G__linked_taginfo G__GROOTDictLN_TGHSplitter;
extern G__linked_taginfo G__GROOTDictLN_GRootBrowser;
extern G__linked_taginfo G__GROOTDictLN_GRootBrowsercLcLENewBrowserMessages;
extern G__linked_taginfo G__GROOTDictLN_GRootBrowsercLcLEInsertPosition;
extern G__linked_taginfo G__GROOTDictLN_TAttPad;
extern G__linked_taginfo G__GROOTDictLN_TVirtualPad;
extern G__linked_taginfo G__GROOTDictLN_TPad;
extern G__linked_taginfo G__GROOTDictLN_TRootCanvas;
extern G__linked_taginfo G__GROOTDictLN_TLine;
extern G__linked_taginfo G__GROOTDictLN_GMarker;
extern G__linked_taginfo G__GROOTDictLN_vectorlEGMarkermUcOallocatorlEGMarkermUgRsPgR;
extern G__linked_taginfo G__GROOTDictLN_reverse_iteratorlEvectorlEGMarkermUcOallocatorlEGMarkermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GROOTDictLN_TArray;
extern G__linked_taginfo G__GROOTDictLN_TArrayD;
extern G__linked_taginfo G__GROOTDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GROOTDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GROOTDictLN_TH1D;
extern G__linked_taginfo G__GROOTDictLN_TH1;
extern G__linked_taginfo G__GROOTDictLN_GH1D;
extern G__linked_taginfo G__GROOTDictLN_maplEGH1DmUcOintcOlesslEGH1DmUgRcOallocatorlEpairlEGH1DmUsPconstcOintgRsPgRsPgR;
extern G__linked_taginfo G__GROOTDictLN_TFile;
extern G__linked_taginfo G__GROOTDictLN_TDirectoryFile;
extern G__linked_taginfo G__GROOTDictLN_GFile;
extern G__linked_taginfo G__GROOTDictLN_TTree;
extern G__linked_taginfo G__GROOTDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__GROOTDictLN_GTree;
extern G__linked_taginfo G__GROOTDictLN_TChain;
extern G__linked_taginfo G__GROOTDictLN_GChain;

/* STUB derived class for protected member access */
